// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module('dcModule', ['dcModule.templates']).directive("dcLine", function($compile) {
    if (!dc || !d3 || !crossfilter || !_) {
      throw 'You need to load DC, D3, Crossfilter and Underscore library';
    }
    return {
      scope: {
        data: '=',
        dimensions: '='
      },
      transclude: true,
      templateUrl: 'dc/line/template.html',
      controller: function() {},
      link: function(scope, element, attrs, controller) {
        var dcLine, setGroups;
        setGroups = function() {
          var item, _i, _len, _ref;
          scope.groups = {};
          _ref = scope.dimensions;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            item = _ref[_i];
            scope.groups[item] = [];
          }
          return console.log(scope.groups);
        };
        scope.$watch('data', function(data) {
          if (data) {
            data.dimension(function(d) {
              var item, _i, _len, _ref;
              _ref = scope.dimensions;
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                item = _ref[_i];
                scope.groups[item].push(d[item]);
              }
            });
          }
        });
        scope.$watch('dimensions', function(data) {
          if (data) {
            return setGroups();
          }
        });
        dcLine = dc.lineChart(element[0]);
        return dcLine.width(250).height(250).margins({
          top: 40,
          right: 50,
          bottom: 30,
          left: 60
        }).dimension(scope.groups).group(crimeIncidentByYear, "Total by Year");
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=dc-line.map
*/
