// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  if (!dc || !d3 || !crossfilter || !_) {
    throw 'You need to load DC, D3, Crossfilter and Underscore library';
  }

  angular.module('dcLine', []).directive("dcLine", function() {
    return {
      scope: {
        data: '=',
        dimensions: '='
      },
      templateUrl: 'dc/line/template.html',
      link: function($scope, element, attrs) {
        var _this = this;
        $scope.chartId = attrs.id ? attrs.id : 'dcLineDefault';
        $scope.height = attrs.height ? attrs.height : 150;
        $scope.$watch('data', function(data) {
          if (data) {
            $scope.chartData = data;
            $scope.dcLineChart = dc.lineChart('#' + $scope.chartId);
            $scope.create();
          }
        });
        $scope.create = function() {
          var dateDimensions, maxDate, minDate, totalSum;
          dateDimensions = $scope.chartData.dimension(function(d) {
            return d['DATETIME:date'];
          });
          totalSum = dateDimensions.group().reduceSum(function(d) {
            return d['MEASURE:Customer Price'];
          });
          minDate = dateDimensions.bottom(1)[0]['DATETIME:date'];
          maxDate = dateDimensions.top(1)[0]['DATETIME:date'];
          $scope.dcLineChart.width(element.width()).height($scope.height).margins({
            top: 10,
            left: 50,
            right: 10,
            bottom: 50
          }).dimension(dateDimensions).group(totalSum, "Price").x(d3.time.scale().domain([minDate, maxDate])).yAxisLabel("Total").xAxisLabel("Data").elasticY(true);
          $scope.dcLineChart.render();
        };
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=dc-line.map
*/
