// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  if (!dc || !d3 || !crossfilter || !_) {
    throw 'You need to load DC, D3, Crossfilter and Underscore library';
  }

  angular.module('dcPie', []).directive("dcPie", function() {
    return {
      scope: {
        dcPie: '='
      },
      templateUrl: 'dc/pie/template.html',
      link: function($scope, element, attrs) {
        var _this = this;
        $scope.chartId = attrs.id ? attrs.id : 'dcPieDefault';
        $scope.height = attrs.height ? attrs.height : 150;
        $scope.dcPieChart = dc.pieChart('#' + $scope.chartId);
        $scope.$watch('dcPie', function(dcPie) {
          if (dcPie) {
            $scope.create();
          }
        });
        $scope.create = function() {
          $scope.dcPieChart.width(element.width()).height($scope.height).dimension($scope.dcPie.dimension()).group($scope.dcPie.sum());
          $scope.dcPieChart.render();
        };
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=dc-pie.map
*/
