// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module('dcModule.templates', []).run(function($templateCache) {
    $templateCache.put("dc/line/template.html", "<div id='{{ chartId }}' class='line-chart'>" + "</div>");
    $templateCache.put("dc/pie/template.html", "<div id='{{ chartId }}' class='pie-chart'>" + "</div>");
  });

}).call(this);

/*
//@ sourceMappingURL=template.map
*/
