// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module('dcModule.templates', []).run(function($templateCache) {
    $templateCache.put("dc/line/template.html", "<div>" + "<h4>Line Chart</h4>" + "<div id='dcLine' class='line-chart'>" + "</div>" + "</div>");
  });

}).call(this);

/*
//@ sourceMappingURL=template.map
*/
