// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  angular.module('angularDcjsApp').controller('MainController', [
    '$scope', 'Debug', 'dataAPI', function($scope, Debug, dataAPI) {
      $scope.measures = [];
      $scope.dimensions = [];
      $scope.datetime = [];
      $scope.gridsterOpts = {
        margins: [20, 20],
        draggable: {
          enabled: true
        },
        resizable: {
          enabled: false
        }
      };
      $scope.customItems = [
        {
          sizeX: 2,
          sizeY: 1,
          row: 0,
          col: 0
        }, {
          sizeX: 2,
          sizeY: 2,
          row: 0,
          col: 2
        }, {
          sizeX: 1,
          sizeY: 1,
          row: 0,
          col: 4
        }
      ];
      $scope.getLog = function() {
        return Debug.output();
      };
      $scope.retrieveData = function() {
        dataAPI.getData().then(function(response) {
          if (response.data) {
            response.data.forEach(function(d) {
              d['DATETIME:date'] = d3.time.format("%m/%d/%Y").parse(d['DATETIME:date']);
            });
            $scope.rows = crossfilter(response.data);
            $scope.lineChartDim = $scope.rows.dimension(function(d) {
              return [d['DATETIME:date']];
            });
            $scope.pieChartDim = $scope.rows.dimension(function(d) {
              return d['DIMENSION:Asset/Content Flavor'];
            });
            $scope.setChartDim();
            $scope.identifyHeaders(response.data);
          }
        });
      };
      $scope.identifyHeaders = function(data) {
        $scope.getParams(data, 'Datetime');
        $scope.getParams(data, 'Dimension');
        return $scope.getParams(data, 'Measure');
      };
      $scope.setChartDim = function() {
        $scope.lineChartOpts = {
          data: $scope.rows,
          dimension: $scope.lineChartDim,
          sum: $scope.lineChartDim.group().reduceSum(function(d) {
            return d['MEASURE:Customer Price'];
          }),
          minDate: $scope.lineChartDim.bottom(1)[0]['DATETIME:date'],
          maxDate: $scope.lineChartDim.top(1)[0]['DATETIME:date']
        };
        return $scope.pieChartOpts = {
          data: $scope.rows,
          dimension: $scope.pieChartDim,
          sum: $scope.pieChartDim.group().reduceSum(function(d) {
            return d['MEASURE:Customer Price'];
          })
        };
      };
      $scope.getParams = function(data, index) {
        var items, pattern;
        if (data && index) {
          items = [];
          pattern = new RegExp(index.toUpperCase() + ':(.*)');
          angular.forEach(data[0], function(value, key) {
            var input;
            input = key.match(pattern);
            if (input) {
              return items.push(input[1]);
            }
          });
          if (items.length > 0) {
            $scope[index] = items;
            return Debug.input({
              name: index,
              'items': items
            });
          }
        }
      };
      $scope.retrieveData();
      $scope.generateDimensions = function() {
        return angular.forEach($scope.Dimension, function(value, key) {
          var dimensions;
          dimensions = $scope.rows.dimension(function(d) {
            return d['DIMENSION:' + value];
          });
          return angular.forEach(dimensions.group().all(), function(value2, key2) {
            return $scope.filterSource.push('DIMENSION:' + value + ':' + value2.key);
          });
        });
      };
      $scope.generateMeasures = function() {
        return angular.forEach($scope.Measure, function(value, key) {
          var dimensions;
          dimensions = $scope.rows.dimension(function(d) {
            return d['MEASURE:' + value];
          });
          return angular.forEach(dimensions.group().all(), function(value2, key2) {
            return $scope.filterSource.push('MEASURE:' + value + ':' + value2.key);
          });
        });
      };
      $scope.generateDatetime = function() {
        return angular.forEach($scope.Datetime, function(value, key) {
          var dimensions;
          dimensions = $scope.rows.dimension(function(d) {
            return d['DATETIME:' + value];
          });
          return angular.forEach(dimensions.group().all(), function(value2, key2) {
            return $scope.filterSource.push('DATETIME:' + value + ':' + value2.key.toUTCString());
          });
        });
      };
      $scope.filter = function() {
        if ($scope.pieChartOpts.dimension) {
          $scope.pieChartOpts.dimension.filter(function(d) {
            if (d === $scope.include) {
              return d;
            }
          });
        }
      };
      $scope.useFilter = function() {};
      return $scope.removeFilter = function() {};
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
