// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  angular.module('angularDcjsApp').controller('MainController', [
    '$scope', 'Debug', 'dataAPI', function($scope, Debug, dataAPI) {
      $scope.measures = [];
      $scope.dimensions = [];
      $scope.datetime = [];
      $scope.searchData = [];
      $scope.select2Opt = {
        'multiple': true,
        'simples_tags': true,
        'tags': [$scope.measures, $scope.dimensions, $scope.datetime]
      };
      $scope.getLog = function() {
        return Debug.output();
      };
      $scope.retrieveData = function() {
        dataAPI.getData().then(function(response) {
          if (response.data) {
            response.data.forEach(function(d) {
              d['DATETIME:date'] = d3.time.format("%m/%d/%Y").parse(d['DATETIME:date']);
            });
            $scope.rows = crossfilter(response.data);
            $scope.myDim = $scope.rows.dimension(function(d) {
              return d['DATETIME:date'];
            });
            $scope.setChartDim();
            $scope.identifyHeaders(response.data);
          }
        });
      };
      $scope.identifyHeaders = function(data) {
        $scope.getParams(data, 'Datetime');
        $scope.getParams(data, 'Dimension');
        return $scope.getParams(data, 'Measure');
      };
      $scope.setChartDim = function() {
        $scope.lineChartOpts = {
          dimension: function() {
            return $scope.rows.dimension(function(d) {
              return d['DATETIME:date'];
            });
          },
          sum: function() {
            return this.dimension().group().reduceSum(function(d) {
              return d['MEASURE:Customer Price'];
            });
          },
          minDate: function() {
            return this.dimension().bottom(1)[0]['DATETIME:date'];
          },
          maxDate: function() {
            return this.dimension().top(1)[0]['DATETIME:date'];
          }
        };
        $scope.pieChartOpts = {
          dimension: function() {
            return $scope.rows.dimension(function(d) {
              return d['DIMENSION:Asset/Content Flavor'];
            });
          },
          sum: function() {
            return this.dimension().group().reduceSum(function(d) {
              return d['MEASURE:Customer Price'];
            });
          }
        };
        $scope.pieChartOpts2 = {
          dimension: function() {
            return $scope.rows.dimension(function(d) {
              return d['DIMENSION:Title'];
            });
          },
          sum: function() {
            return this.dimension().group().reduceSum(function(d) {
              return d['MEASURE:Customer Price'];
            });
          }
        };
      };
      $scope.getParams = function(data, index) {
        var items, pattern;
        if (data && index) {
          items = [];
          pattern = new RegExp(index.toUpperCase() + ':(.*)');
          angular.forEach(data[0], function(value, key) {
            var input;
            input = key.match(pattern);
            if (input) {
              return items.push(input[1]);
            }
          });
          if (items.length > 0) {
            $scope[index] = items;
            return Debug.input({
              name: index,
              'items': items
            });
          }
        }
      };
      $scope.retrieveData();
      $scope.generateDimensions = function() {
        return angular.forEach($scope.Dimension, function(value, key) {
          var dimensions;
          dimensions = $scope.rows.dimension(function(d) {
            return d['DIMENSION:' + value];
          });
          return angular.forEach(dimensions.group().all(), function(value2, key2) {
            return $scope.filterSource.push('DIMENSION:' + value + ':' + value2.key);
          });
        });
      };
      $scope.generateMeasures = function() {
        return angular.forEach($scope.Measure, function(value, key) {
          var dimensions;
          dimensions = $scope.rows.dimension(function(d) {
            return d['MEASURE:' + value];
          });
          return angular.forEach(dimensions.group().all(), function(value2, key2) {
            return $scope.filterSource.push('MEASURE:' + value + ':' + value2.key);
          });
        });
      };
      $scope.generateDatetime = function() {
        return angular.forEach($scope.Datetime, function(value, key) {
          var dimensions;
          dimensions = $scope.rows.dimension(function(d) {
            return d['DATETIME:' + value];
          });
          return angular.forEach(dimensions.group().all(), function(value2, key2) {
            return $scope.filterSource.push('DATETIME:' + value + ':' + value2.key.toUTCString());
          });
        });
      };
      $scope.useFilter = function() {
        var input, pattern;
        if ($scope.include) {
          $scope.exclude = null;
          pattern = new RegExp('(.*):(.*):(.*)');
          input = $scope.include.match(pattern);
          if (input) {
            if (input.length >= 4) {
              if (input[3] !== "") {
                $scope.filter = {
                  dimension: input[1] + ':' + input[2],
                  value: input[3]
                };
                $scope.setFilter();
              } else {
                if ($scope.newFilter) {
                  $scope.newFilter.filter(null);
                }
              }
            }
          }
        }
      };
      $scope.setFilter = function() {
        $scope.newFilter = $scope.rows.dimension(function(d) {
          return d['DATETIME:date'];
        });
        $scope.newFilter.filter($scope.filter.value);
        return dc.redrawAll();
      };
      return $scope.removeFilter = function() {};
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
