// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var Debug;

  Debug = function() {
    this.message = [];
    this.output = function() {
      return this.message;
    };
    this.input = function(message) {
      this.message.push(message);
    };
    this.clear = function() {
      this.message = [];
    };
  };

  describe("Service: Debug", function() {
    beforeEach(function() {
      return module('angularDcjsApp');
    });
    it("should be an instance of Debug", function() {
      return expect(Debug).toBe instanceof Debug;
    });
    it("should have no messages", function() {
      var debug;
      debug = new Debug();
      return expect(debug.output().length).toEqual(0);
    });
    it("should have input a message", function() {
      var debug;
      debug = new Debug();
      debug.input('Test');
      return expect(debug.output().length).toEqual(1);
    });
    return it("should have input a message and clear", function() {
      var debug;
      debug = new Debug();
      debug.input('Test');
      expect(debug.output().length).toEqual(1);
      debug.clear();
      return expect(debug.output().length).toEqual(0);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=debug.map
*/
