// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  describe("Service: Debug", function() {
    var Debug;
    Debug = void 0;
    beforeEach(function() {
      return module('angularDcjsApp');
    });
    beforeEach(inject(function(_Debug_) {
      return Debug = _Debug_;
    }));
    it("should have no messages", function() {
      return expect(Debug.output().length).toEqual(0);
    });
    it("should have input a message", function() {
      Debug.input('Test');
      return expect(Debug.output().length).toEqual(1);
    });
    return it("should have input a message and clear", function() {
      Debug.input('Test');
      expect(Debug.output().length).toEqual(1);
      Debug.clear();
      return expect(Debug.output().length).toEqual(0);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=debug.map
*/
