// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  describe("Directive: PivotTable", function() {
    var data, dataResponse, element, scope;
    scope = void 0;
    element = void 0;
    data = void 0;
    dataResponse = void 0;
    beforeEach(function() {
      module("PivotTable");
    });
    beforeEach(inject(function($rootScope) {
      scope = $rootScope.$new();
      return dataResponse = [
        {
          "DATETIME:date": "9/27/13",
          "MEASURE:Units": 1,
          "MEASURE:Royalty Price": 3.49,
          "MEASURE:Customer Price": 4.99,
          "DIMENSION:Vendor Identifier": "0144_20121109",
          "DIMENSION:Title": "Headh",
          "DIMENSION:Label/Studio/Network": "Yello",
          "DIMENSION:Product Type Identifier": "D",
          "DIMENSION:Order Id": "5.02E+09",
          "DIMENSION:Postal Code": "49915-2504",
          "DIMENSION:Customer Identifier": 2240000173,
          "DIMENSION:Sale/Return": "S",
          "DIMENSION:Customer Currency": "USD",
          "DIMENSION:Country Code": "CL",
          "DIMENSION:Royalty Currency": "USD",
          "DIMENSION:Asset/Content Flavor": "HD"
        }, {
          "DATETIME:date": "9/24/13",
          "MEASURE:Units": 1,
          "MEASURE:Royalty Price": 1.39,
          "MEASURE:Customer Price": 1.99,
          "DIMENSION:Vendor Identifier": "0099_20120827",
          "DIMENSION:Title": "A Ond",
          "DIMENSION:Label/Studio/Network": "Const",
          "DIMENSION:Product Type Identifier": "D",
          "DIMENSION:Order Id": "2.03E+09",
          "DIMENSION:Postal Code": "29284-3466",
          "DIMENSION:Customer Identifier": 1642627348,
          "DIMENSION:Sale/Return": "S",
          "DIMENSION:Customer Currency": "USD",
          "DIMENSION:Country Code": "BR",
          "DIMENSION:Royalty Currency": "USD",
          "DIMENSION:Asset/Content Flavor": "SD"
        }, {
          "DATETIME:date": "9/29/13",
          "MEASURE:Units": 1,
          "MEASURE:Royalty Price": 3.49,
          "MEASURE:Customer Price": 4.99,
          "DIMENSION:Vendor Identifier": "0144_20121109",
          "DIMENSION:Title": "Headh",
          "DIMENSION:Label/Studio/Network": "Yello",
          "DIMENSION:Product Type Identifier": "D",
          "DIMENSION:Order Id": "5.70E+09",
          "DIMENSION:Postal Code": "26586-2424",
          "DIMENSION:Customer Identifier": 4967191007,
          "DIMENSION:Sale/Return": "S",
          "DIMENSION:Customer Currency": "USD",
          "DIMENSION:Country Code": "CO",
          "DIMENSION:Royalty Currency": "USD",
          "DIMENSION:Asset/Content Flavor": "HD"
        }, {
          "DATETIME:date": "9/28/13",
          "MEASURE:Units": 1,
          "MEASURE:Royalty Price": 2.79,
          "MEASURE:Customer Price": 3.99,
          "DIMENSION:Vendor Identifier": "0144_20121109",
          "DIMENSION:Title": "Headh",
          "DIMENSION:Label/Studio/Network": "Yello",
          "DIMENSION:Product Type Identifier": "D",
          "DIMENSION:Order Id": "3.05E+09",
          "DIMENSION:Postal Code": "23322-2800",
          "DIMENSION:Customer Identifier": 3573922889,
          "DIMENSION:Sale/Return": "S",
          "DIMENSION:Customer Currency": "USD",
          "DIMENSION:Country Code": "CL",
          "DIMENSION:Royalty Currency": "USD",
          "DIMENSION:Asset/Content Flavor": "SD"
        }, {
          "DATETIME:date": "9/23/13",
          "MEASURE:Units": 1,
          "MEASURE:Royalty Price": 2.09,
          "MEASURE:Customer Price": 2.99,
          "DIMENSION:Vendor Identifier": "0211_20132108",
          "DIMENSION:Title": "AlÃŒÂ©m",
          "DIMENSION:Label/Studio/Network": "Wakin",
          "DIMENSION:Product Type Identifier": "D",
          "DIMENSION:Order Id": "4.34E+09",
          "DIMENSION:Postal Code": "18509-2108",
          "DIMENSION:Customer Identifier": 4368359068,
          "DIMENSION:Sale/Return": "S",
          "DIMENSION:Customer Currency": "USD",
          "DIMENSION:Country Code": "BR",
          "DIMENSION:Royalty Currency": "USD",
          "DIMENSION:Asset/Content Flavor": "HD"
        }, {
          "DATETIME:date": "9/28/13",
          "MEASURE:Units": 1,
          "MEASURE:Royalty Price": 1.39,
          "MEASURE:Customer Price": 1.99,
          "DIMENSION:Vendor Identifier": "0145_20121109",
          "DIMENSION:Title": "Habem",
          "DIMENSION:Label/Studio/Network": "Sache",
          "DIMENSION:Product Type Identifier": "D",
          "DIMENSION:Order Id": "3.77E+09",
          "DIMENSION:Postal Code": "16346-1910",
          "DIMENSION:Customer Identifier": 4481458708,
          "DIMENSION:Sale/Return": "S",
          "DIMENSION:Customer Currency": "USD",
          "DIMENSION:Country Code": "BR",
          "DIMENSION:Royalty Currency": "USD",
          "DIMENSION:Asset/Content Flavor": "SD"
        }
      ];
    }));
    it("should start directive", inject(function($compile) {
      element = angular.element('<div id="#chart6" pivot-table data="rows"></div>');
      element = $compile(element)(scope);
      return expect(element.html()).not.toBeNull;
    }));
    it("should load pivot", function() {
      return expect(jQuery.pivotUI).not.toBeNull;
    });
    return it("should render pivot", function() {
      return expect(jQuery(element).pivotUI(dataResponse)).not.toBeNull;
    });
  });

}).call(this);

/*
//@ sourceMappingURL=pivottable.map
*/
