// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  if (!dc || !d3 || !crossfilter || !_) {
    throw 'You need to load Pivot';
  }

  angular.module('PivotTable', []).directive("pivotTable", function() {
    return {
      restrict: 'AC',
      scope: {
        data: '=',
        pivotTable: '='
      },
      template: '<div></div>',
      link: function($scope, element, attrs) {
        $scope.create = function() {
          return element.pivotUI($scope.data);
        };
        return $scope.$watch('data', function(data) {
          return $scope.create();
        });
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=pivottable.map
*/
