// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  describe("Controller:MainController", function() {
    beforeEach(module('angularDcjsApp'));
    return it("List should be an array", inject(function($controller, $rootScope) {
      var $scope, controller;
      $scope = $rootScope.$new();
      controller = $controller('MainController', {
        '$scope': $scope
      });
      $scope.list = [];
      return expect($scope.list).toEqual([]);
    }));
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
