// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module('angularDcjsApp').service("dataAPI", function($http, $q) {
    this.getData = function() {
      return $http.get('sampledata2.json');
    };
    this.getScreenParams = function() {
      return $http.get('screen.json');
    };
  });

}).call(this);

/*
//@ sourceMappingURL=dataAPI.map
*/
