// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module('angularDcjsApp').service("dataAPI", function($http, $q) {
    this.getData = function() {
      return $http.get('sampledata.json');
    };
  });

}).call(this);

/*
//@ sourceMappingURL=dataAPI.map
*/
