// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module('angularDcjsApp').service('debug', function() {
    return this.test = 'ola';
  });

}).call(this);

/*
//@ sourceMappingURL=debug.map
*/
