// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  angular.module('angularDcjsApp', ['ngRoute', 'gridster']).config(function($routeProvider) {
    return $routeProvider.when("/", {
      controller: 'MainController',
      templateUrl: 'views/main.html'
    }).otherwise({
      redirectTo: "/"
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
